# Generated by Django 5.0.9 on 2026-07-16 21:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('faculty', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('active', 'Active'), ('completed', 'Completed')], default='scheduled', max_length=10)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='academics.classroom')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='faculty.facultyprofile')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='academics.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='academics.subject')),
            ],
            options={
                'db_table': 'attendance_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UnknownFaceLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('no_match', 'No enrolled match found'), ('low_confidence', 'Low confidence match'), ('spoof_suspected', 'Spoof attempt suspected'), ('not_enrolled', 'Face not enrolled')], max_length=20)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('frame_image', models.ImageField(blank=True, null=True, upload_to='session_frames/%Y/%m/')),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='students.student')),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.classroom')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unknown_face_logs', to='attendance.attendancesession')),
            ],
            options={
                'db_table': 'unknown_face_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('absent', 'Absent'), ('spoof_detected', 'Spoof Detected')], default='absent', max_length=15)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('method', models.CharField(choices=[('auto', 'Automatic (AI)'), ('manual', 'Manual Correction')], default='auto', max_length=10)),
                ('marked_at', models.DateTimeField(blank=True, null=True)),
                ('needs_verification', models.BooleanField(default=False)),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_corrections', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='students.student')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='attendance.attendancesession')),
            ],
            options={
                'db_table': 'attendance_records',
                'ordering': ['-marked_at'],
                'unique_together': {('session', 'student')},
            },
        ),
    ]
