# Generated by Django 5.0.9 on 2026-07-16 21:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('roll_no', models.CharField(max_length=20, unique=True)),
                ('admission_year', models.PositiveSmallIntegerField()),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('face_enrollment_status', models.CharField(choices=[('not_enrolled', 'Not Enrolled'), ('pending', 'Pending Review'), ('enrolled', 'Enrolled'), ('rejected', 'Rejected')], default='not_enrolled', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academics.course')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academics.section')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'students',
                'ordering': ['roll_no'],
            },
        ),
        migrations.CreateModel(
            name='FaceEmbedding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vector', models.JSONField(help_text='512-d float embedding from the recognition model.')),
                ('sample_image', models.ImageField(upload_to='face_samples/%Y/%m/')),
                ('quality_score', models.FloatField(default=0.0)),
                ('pose_label', models.CharField(blank=True, max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_embeddings', to='students.student')),
            ],
            options={
                'db_table': 'face_embeddings',
                'ordering': ['-created_at'],
            },
        ),
    ]
